apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s: 
      volumeClaimTemplate:
        spec:
          storageClassName: odf-volume
          volumeMode: Filesystem
          resources:
            requests:
              storage: 30Gi
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName:  odf-volume
          resources:
            requests:
              storage: 10Gi
