apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: openshift-logging
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 9
      storage: {}
      resources: 
        limits:
          memory: 736Mi
        requests:
          cpu: 100m
          memory: 300Mi
      proxy:
        resources: 
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 256Mi
  visualization:
    type: "kibana"
    kibana:
      resources: 
        limits:
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 100Mi
      replicas: 1
  collection:
    logs:
      type: "fluentd"
      fluentd:
        resources: 
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 256Mi
  http.compression: true

